### ISSUE TITLE
Plugin usage unclear according to docs

### ISSUE THREAD

**Issue by andig** [grafana/grafana-image-renderer#106]
**What would you like to be added**:

Clear explanation what purpose this plugin fulfills and where it differs from the integrated `Share` -> `Direct link rendered image` functionality.

**Why is this needed**:

Docs state that:

> Grafana supports automatic rendering of panels and dashboards as PNG images. 

It seems that this functionality already exists as `View` -> `Share` -> `Direct link rendered image`.

Additionally, docs also points (or redirects) to `https://grafana.com/docs/grafana/latest/administration/image_rendering/%7B%7B%20%3C%20relref%20%22/installation/docker/#build-with-grafana-image-renderer-plugin-pre-installed"%20>%20}}` which doesn't exist.

**Comment by marefr** [comment]
All information needed should be in 
- https://grafana.com/grafana/plugins/grafana-image-renderer
- https://grafana.com/docs/grafana/latest/administration/image_rendering/ 
- https://grafana.com/docs/grafana/latest/reference/share_panel/#direct-link-rendered-image

Will close this. Let us know if you're still lacking information and we'll consider reopen this. Thanks

**Comment by andig** [comment]
After reading through all three links my question is the same: what functionality does this plugin provide that the default docker container does not? Image rendering seems part of standard docker.

Three thumbs seem to confirm this is causing common confusion so an answer would be appreciated.

**Comment by marefr** [comment]
@andig the reason is PhantomJS (which is pre-packaged with Grafana currently) is a dead project and not really a proper browser and is not something we want to continue build upon moving forward. Plugin/remote rendering service uses headless chrome.

That's why we deprecated PhantomJS in Grafana v6.4, see [release notes](https://grafana.com/docs/grafana/latest/guides/whats-new-in-v6-4/#phantomjs-deprecation) and [changelog](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#deprecation-notes) 

For Grafana v7.0 we plan to remove PhantomJS (https://github.com/grafana/grafana/issues/13802)

**Comment by andig** [comment]
@marefr looking at https://github.com/grafana/grafana/issues/22965, will the chrome headless improve the abysmal rendering performance? If not by itself- should I migrate that issue over here?

**Comment by marefr** [comment]
I just migrated it here
