### ISSUE TITLE
Rendering failed: Error: Failed to  launch chrome! spawn

### ISSUE THREAD

**Issue by anoop2503** [grafana/grafana-image-renderer#121]
**What happened**:
Getting following error in the log when trying to preview the report from "New Report" creation page.

`t=2020-03-25T13:48:06+0000 lvl=eror msg="Panel render error" logger=report panel=12 error="Rendering failed: Error: Failed to
 launch chrome! spawn /var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome ENOENT\n\n\nTROUBLESHOOTING: https:
//github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"`

**What you expected to happen**:
- The report should be generated with images without any issues.

**How to reproduce it (as minimally and precisely as possible)**:
- Run Grafana as docker container
- Install Grafana Image Renderer plugin when building Grafana container image.

**Anything else we need to know?**:
When click on "Preview" button, it opens a new tab for showing report preview. However, all the images are showing "Server Side Rendering Failed" error.

**Environment**:
- Grafana Image Renderer version: 1.0.7
- Grafana version: Grafana Enterprise v6.5.2
- Installed plugin or remote renderer service: 
- OS Grafana Image Renderer is installed on: debian
- User OS & Browser: Windows & Chrome
- Others:

**Comment by marefr** [comment]
You cannot install the plugin in the official Grafana image, you have to build a custom docker image. Please refer to https://grafana.com/docs/grafana/latest/administration/image_rendering/#run-in-custom-grafana-docker-image

If possible, since you already run Grafana in docker container we recommend to run image renderer in a separate docker container.
