### ISSUE TITLE
Request to make image more clear

### ISSUE THREAD

**Issue by xbsura** [grafana/grafana-image-renderer#163]
**What would you like to be added**:
This plugin is ver useful, but the picture Resolution is not so good, I use rendering_viewport_device_scale_factor=3 but still not clear

**Why is this needed**:
I need a param or something to make pic as clear as what it seems in my local chrome

look 
![image](https://user-images.githubusercontent.com/2181072/87853004-4ff50d00-c939-11ea-8450-68d71bf55c55.png)

![image](https://user-images.githubusercontent.com/2181072/87852988-26d47c80-c939-11ea-9284-3c120b5ea63f.png)

**Comment by AgnesToulet** [comment]
The `rendering_viewport_device_scale_factor` setting only sets the default device scale factor. It's used when no other device scale factor is set, for the alerting feature for example. 

If you get your image via the "Direct link rendered image" feature, you need to add `&scale=3` to your render URL `<grafana-url>/render/d-solo/<dashboard slug>/<dashboard name>?orgId=1&from=1623826207523&to=1623847807523&panelId=5&width=1000&height=500&scale=3`) to set the device scale factor, otherwise Grafana sets this to 1 as default (see https://github.com/grafana/grafana/blob/main/pkg/api/render.go#L65).

Please note that, if you want to set it to more than 3, you also need to increase the `rendering_viewport_max_device_scale_factor` as the default is 3.
