### ISSUE TITLE
Publishing a plugin fails due to missing files in the manifest

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana-image-renderer#206]
The final step in the release guide fails - `gcom /plugins -d slug=grafana-image-renderer -d version=2.0.1`

The error is:

```json
{
  "id": "grafana-image-renderer",
  "type": "renderer",
  "url": "https://github.com/grafana/grafana-image-renderer",
  "versions": [
    {
      "version": "2.0.1",
      "commit": "bc7488ad3c20bb2a972c2f1d08a691a6b0c834d8",
      "url": "https://github.com/grafana/grafana-image-renderer",
      "download": {
        "darwin-amd64": {
          "url": "https://github.com/grafana/grafana-image-renderer/releases/download/v2.0.1/plugin-darwin-x64-unknown.zip",
          "md5": "8c46f04e190716066a2665a2f3358795"
        },
        "linux-amd64": {
          "url": "https://github.com/grafana/grafana-image-renderer/releases/download/v2.0.1/plugin-linux-x64-glibc.zip",
          "md5": "45d7a8f31c4cf019793c413831e377e8"
        },
        "windows-amd64": {
          "url": "https://github.com/grafana/grafana-image-renderer/releases/download/v2.0.1/plugin-win32-x64-unknown.zip",
          "md5": "b9acc26af81c2ccdfa4288c8b68100d3"
        }
      },
      "error": "darwin-amd64 zip file: file not found in manifest: chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/XPCServices"
    }
  ]
}
```

Suspect that it is a bug in https://github.com/grafana/build-pipeline/blob/master/pkg/build/manifest.go and if the same code is in Grafana then could be a potential security flaw that needs to be investigated.

**Comment by aknuds1** [comment]
This is a bug in grafana-toolkit AFAICT. `grabpl` rightly (IMO) ignores _dist/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/XPCServices_ when generating the manifest, because it's a symlink to the directory _dist/chrome-mac/Chromium.app/Contents/Frameworks/Chromium Framework.framework/Versions/Current/XPCServices_. Symlinks to directories should be ignored, since you shouldn't checksum directories (only their contents).
