### ISSUE TITLE
grafana-image-render is disabled (Modified signature)

### ISSUE THREAD

**Issue by nicolargo** [grafana/grafana-image-renderer#296]
**What happened**:

I upgrade the plugin to version 3.2.0, the following message is displayed:

![image](https://user-images.githubusercontent.com/776747/136407147-40551aed-d420-437c-be3b-20380b95d416.png)

**What you expected to happen**:

the plugin should be loaded...

**How to reproduce it (as minimally and precisely as possible)**:

Upload the plugin, restart the Grafana server.

**Anything else we need to know?**:

**Environment**:
- Grafana Image Renderer version: 3.2.0
- Grafana version: 8.1.7
- Installed plugin or remote renderer service: no render service
- OS Grafana Image Renderer is installed on: CentOS 7.9
- User OS & Browser: Windows + Firefox

**Comment by AgnesToulet** [comment]
Hi, thanks for reporting this! Can you add your grafana logs in the issue? They should contain a bit more information on which files are causing this error.

Also, this issue may occur because of the upgrade that does not delete old files. Which version did you have before the upgrade? Is it working if you uninstall the plugin entirely and install it again?
